clean up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -386,8 +386,8 @@ jobs:
             export OldWorkflowID=$(aws cloudformation list-exports \
             --query "Exports[?Name==\`WorkflowID\`].Value" \
             --no-paginate --output text)
-
             echo $OldWorkflowID >> ~/project/OldWorkflowID.txt
+            cat ~/project/OldWorkflowID.txt
 
             aws cloudformation deploy \
             --template-file .circleci/files/cloudfront.yml \
@@ -395,9 +395,51 @@ jobs:
             --parameter-overrides WorkflowID="udapeople-${CIRCLE_WORKFLOW_ID:0:7}" \
             --tags project=udapeople
 
+            echo "${OldWorkflowID}"
+            echo CurrentWorflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
+
       # Here's where you will add some code to rollback on failure
       - destroy-environment
       - revert-migrations  
+
+cleanup:
+  docker:
+    # Docker image here
+    - image: amazon/aws-cli
+  steps:
+    # Checkout code from git
+    - checkout
+    - run:
+        name: Get old stack workflow id
+        command: |
+          # your code here
+          export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+          echo OldWorkflowID: "${OldWorkflowID}"
+
+          export STACKS=($(aws cloudformation \
+          list-stacks --query "StackSummaries[*].StackName" 
+          --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+          echo Stack names: "${STACKS[@]}"
+          cat ~/project/OldWorkflowID.txt
+          export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+          echo OldWorkflowID: "${OldWorkflowI
+
+    - run:
+        name: Remove old stacks and files
+        command: |
+            # your code here
+            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+            then
+              echo "----------Delete cofirmed------------"
+              echo "udapeople-${OldWorkflowID}"
+              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
+              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
+              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
+            else
+              echo  "---------Cannot cleanup--------------"
+            fi
+          
 
 
 workflows:
@@ -430,3 +472,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
+      - cleanup:
+          requires: [cloudfront-update]
