clean up

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -414,30 +414,27 @@ jobs:
           command: |
             # your code here
             export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-              echo Stack names: "${STACKS[@]}"
-              cat ~/OldWorkflowID.txt
-              export OldWorkflowID=$(cat ~/OldWorkflowID.txt)
-              echo OldWorkflowID: "${OldWorkflowID}"
+            --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+            echo Stack names: "${STACKS[@]}"
+            cat ~/project/OldWorkflowID.txt
+            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+            echo OldWorkflowID: "${OldWorkflowID}"
             
 
       - run:
           name: Remove old stacks and files
           command: |
-            cat ~/OldWorkID.txt
-            OldWorkID=$(cat ~/OldWorkID.txt)
-            echo OldWorkflowID: "${OldWorkflowID}"
-            echo OldWorkflowID
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then
-              echo "----------Delete cofirmed------------"
-              echo "udapeople-${OldWorkflowID}"
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive 
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" 
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" 
-            else
-              echo  "---------Cannot cleanup--------------"
-            fi
+            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+              if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+              then
+                echo "----------Deletes cofirmed------------"
+                echo "udapeople-${OldWorkflowID}"
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
+                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
+                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
+              else
+                echo  "---------Cannot cleanup--------------"
+              fi
           
 
 
