deploy backend updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -299,78 +299,83 @@ jobs:
 
   deploy-backend:
     docker:
+      # Docker image here that supports Ansible
       - image: cimg/python:3.10
     steps:
+      # Checkout code from git
       - checkout
-      - install_awscli
-      - install_nodejs
-      - install_ansible
+      # Add ssh keys with fingerprint
       - add_ssh_keys:
-          fingerprints:
-            - "15:71:24:06:04:09:fb:98:a5:85:17:31:e3:40:8b:03"
-
-      - attach_workspace:
-          at: ~/
+           fingerprints: "15:71:24:06:04:09:fb:98:a5:85:17:31:e3:40:8b:03"
+      # attach workspace
+      - run:
+          name: Install dependencies
+          command: |
+            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible
       - restore_cache:
           keys: [backend-build]
-
-      - run:
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+      - run: 
           name: Deploy backend
           command: |
-            cd backend
-            npm install --legacy-peer-deps
-            npm run build
-            cd ..
-            tar -C backend -czvf artifact.tar.gz .
-            mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
-            mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
-            cd .circleci/ansible
-            echo "Contents of the inventory.txt file is ------$(cat inventory.txt)"
-            ansible-playbook -i inventory.txt deploy-backend.yml
-
+             cd backend
+             npm i
+             npm run build 
+             cd ..
+             # Zip the directory
+             tar -C backend -czvf artifact.tar.gz .
+             mkdir -p ~/project/.circleci/ansible/roles/deploy/files/
+             mv artifact.tar.gz .circleci/ansible/roles/deploy/files/artifact.tar.gz
+             cd .circleci/ansible
+             echo "Contents  of the inventory.txt file is -------"
+             cat inventory.txt
+             ansible-playbook -i inventory.txt deploy-backend.yml
+      # Here's where you will add some code to rollback on failure
       - destroy-environment
-      - revert-migrations
 
-  smoke-test:
-    docker:
-      - image: python:3.7-alpine3.16
-    steps:
-      - checkout
-      - install_awscli
-      - install_nodejs
-      - run:
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --query "Reservations[*].Instances[*].PublicDnsName" \
-            --output text)
-            echo "${API_URL}"
-            export API_URL="http://${BACKEND_IP}:3030"
-      - run:
-          name: Backend smoke test.
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
+  
+  # smoke-test:
+  #   docker:
+  #     - image: python:3.7-alpine3.16
+  #   steps:
+  #     - checkout
+  #     - install_awscli
+  #     - install_nodejs
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances \
+  #           --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #           --query "Reservations[*].Instances[*].PublicDnsName" \
+  #           --output text)
+  #           echo "${API_URL}"
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+  #             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --output text)
 
-            export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-            echo "API_URL = ${API_URL}"
-            echo "Wait for Server to accept GET connection request:"
-            sleep 60
-            if [[ 'ok' =~ $(curl -s --connect-timeout 5 ${API_URL}/api/status | grep -o ok) ]];then return 0 else return 1;fi
+  #           export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+  #           echo "API_URL = ${API_URL}"
+  #           echo "Wait for Server to accept GET connection request:"
+  #           sleep 60
+  #           if [[ 'ok' =~ $(curl -s --connect-timeout 5 ${API_URL}/api/status | grep -o ok) ]];then return 0 else return 1;fi
             
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
-            if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-            then
-               exit 0
-            else
-               exit 1
-            fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
+  #           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+  #           then
+  #              exit 0
+  #           else
+  #              exit 1
+  #           fi
       
 
 workflows:
@@ -399,5 +404,5 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
